// Deterministic naming conventions (no AI hallucination)
export const IR_NAMING = {
  toTableName:    (entity) => entity.toLowerCase().replace(/\s+/g, "_") + "s",
  toColumnName:   (field)  => field.toLowerCase().replace(/\s+/g, "_"),
  toEndpointPath: (entity, action) => {
    const base = "/" + entity.toLowerCase().replace(/\s+/g, "-") + "s";
    const map = {
      list: "GET " + base,
      create: "POST " + base,
      read: "GET " + base + "/:id",
      update: "PUT " + base + "/:id",
      delete: "DELETE " + base + "/:id"
    };
    return map[action] || "GET " + base;
  },
  toPageRoute: (name) => "/" + name.toLowerCase().replace(/\s+/g, "-"),
  toEPId: (entity, action) => `EP_${entity.toUpperCase()}_${action.toUpperCase()}`,
};

// Build deterministic IR from lexer + parser output
export const buildIR = (lexerData, parserData) => {
  const tokens    = lexerData?.tokens || {};
  const ast       = parserData?.intent_ast || {};
  const entities  = [...new Set([...(tokens.entities || []), ...(ast.entities || []).map(e => e.name)])];
  const roles     = [...new Set([...(tokens.roles || []), ...(ast.user_flows || []).map(f => f.role)])];
  const features  = tokens.core_features || [];
  const fg        = ast.feature_graph || {};

  // Deterministic table names
  const tables = entities.map(e => ({
    entity:    e,
    tableName: IR_NAMING.toTableName(e),
    columns: [
      { name: "id",         type: "uuid",         primary: true,  nullable: false, unique: false },
      { name: "created_at", type: "timestamp",    primary: false, nullable: false, unique: false, default: "NOW()" },
      { name: "updated_at", type: "timestamp",    primary: false, nullable: false, unique: false, default: "NOW()" },
    ]
  }));

  // Deterministic endpoint IDs
  const endpointMap = {};
  entities.forEach(e => {
    ["list", "create", "read", "update", "delete"].forEach(action => {
      const id = IR_NAMING.toEPId(e, action);
      endpointMap[id] = { entity: e, action, path: IR_NAMING.toEndpointPath(e, action) };
    });
  });

  // Deterministic page routes
  const corePages = ["Dashboard", "Login", ...entities.map(e => e + " List"), ...entities.map(e => e + " Detail")];

  return {
    version:   "1.0",
    appName:   ast.app_name || tokens.app_type || "App",
    appType:   tokens.app_type || "web",
    entities,
    roles,
    features,
    tables,
    endpointMap,
    corePages,
    hasPayments:  features.some(f => /pay|stripe|billing|subscri/i.test(f)) || fg.payments || false,
    hasAnalytics: features.some(f => /analytic|dashboard|chart|report/i.test(f)) || false,
    hasRealtime:  features.some(f => /realtime|websocket|live|chat/i.test(f)) || fg.real_time || false,
    hasUploads:   features.some(f => /upload|file|image|photo/i.test(f)) || fg.file_uploads || false,
    authType:     fg.auth_type || "jwt",
    monetization: tokens.monetization || "free",
    complexity:   tokens.complexity || "medium",
    confidence:   lexerData?.confidence || 0.8,
    ambiguities:  tokens.ambiguities || [],
    assumptions:  tokens.assumptions || [],
  };
};

export const generateReactCode = (irData, codegenData) => {
  if (!irData || !codegenData) return null;

  const pages = codegenData.ui_schema?.pages || [];
  const endpoints = codegenData.api_schema?.endpoints || [];
  const authRoutes = codegenData.auth_schema?.routes || {};

  // Generate API service file
  const apiService = `// AUTO-GENERATED by FORGE v4
// App: ${irData.appName}
// DO NOT EDIT MANUALLY

const API_BASE = process.env.NEXT_PUBLIC_API_URL || "/api/v1";

const apiRequest = async (method, path, body, token) => {
  const res = await fetch(API_BASE + path, {
    method,
    headers: {
      "Content-Type": "application/json",
      ...(token ? { Authorization: \`Bearer \${token}\` } : {}),
    },
    ...(body ? { body: JSON.stringify(body) } : {}),
  });
  if (!res.ok) throw new Error(\`HTTP \${res.status}\`);
  return res.json();
};

${endpoints.slice(0, 6).map(ep => {
  const fnName = ep.id.toLowerCase().replace(/_/g, "");
  const hasBody = Object.keys(ep.body || {}).length > 0;
  const hasQuery = (ep.query || []).length > 0;
  return `export const ${fnName} = (${hasBody ? "body, " : ""}${hasQuery ? "params, " : ""}token) =>
  apiRequest("${ep.method}", "${ep.path}"${hasBody ? ", body" : ""}, token);`;
}).join("\n\n")}`;

  // Generate page components
  const pageComponents = pages.slice(0, 4).map(page => {
    const compName = page.name.replace(/\s+/g, "");
    const layout = page.layout || "sidebar";
    const layoutTag = layout === "sidebar" ? "SidebarLayout" : "TopNavLayout";
    const componentTags = (page.components || []).map(c => `<${c.replace(/\s+/g, "")} />`).join("\n      ");
    return `// Page: ${page.name}  Route: ${page.route}
// Auth: ${page.auth ? `Required · Roles: ${(page.roles || []).join(", ")}` : "Public"}
export default function ${compName}Page() {
  return (
    <${layoutTag}>
      <PageHeader title="${page.name}" />
      ${componentTags}
    </${layoutTag}>
  );
}`;
  }).join("\n\n");

  // Generate route config
  const routeConfig = `// Next.js App Router configuration
// AUTO-GENERATED by FORGE v4

export const routes = [
${pages.map(p => `  { path: "${p.route}", component: "${p.name.replace(/\s+/g, "")}Page", auth: ${p.auth}, roles: ${JSON.stringify(p.roles || [])} },`).join("\n")}
];

export const authRoutes = {
${Object.entries(authRoutes).map(([k, v]) => `  ${k}: "${v}",`).join("\n")}
};`;

  // Generate DB migration
  const tables = codegenData.db_schema?.tables || [];
  const migration = `-- AUTO-GENERATED by FORGE v4
-- App: ${irData.appName}
-- Run with: psql -d your_db -f migration.sql

${tables.map(table => `CREATE TABLE IF NOT EXISTS ${table.name} (
${(table.columns || []).map(col => {
  let def = `  ${col.name} ${col.type}`;
  if (col.primary) def += " PRIMARY KEY";
  if (!col.nullable && !col.primary) def += " NOT NULL";
  if (col.unique) def += " UNIQUE";
  if (col.default) def += ` DEFAULT ${col.default}`;
  if (col.fk) def += ` REFERENCES ${col.fk}`;
  return def;
}).join(",\n")}
);

${(table.indexes || []).map(idx => `CREATE INDEX IF NOT EXISTS idx_${table.name}_${idx} ON ${table.name}(${idx});`).join("\n")}
`).join("\n")}`;

  return { apiService, pageComponents, routeConfig, migration };
};


